---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: create openvpn server
      ansible.builtin.include_role:
        name: ansible-role-openvpn
      vars:
        openvpn_role: "server"

    - name: copy certificates and keys from the server to the client
      ansible.builtin.copy:
        src: /etc/openvpn/easy-rsa/pki/{{ item }}
        dest: /etc/openvpn/client/{{ item | basename }}
        mode: "0640"
        remote_src: yes
      loop:
        - ca.crt
        - issued/client.crt
        - private/client.key
        - ta.key

    - name: create openvpn client
      ansible.builtin.include_role:
        name: ansible-role-openvpn
      vars:
        openvpn_role: "client"
        openvpn_client_server: "127.0.0.1"
