---
#
# Ansible managed
#
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: "openvpn-${image:-docker-ubuntu-systemd}-${tag:-focal}${TOX_ENVNAME}"
    image: "${namespace:-buluma}/${image:-docker-ubuntu-systemd}:${tag:-focal}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: yes
    pre_build_image: yes
provisioner:
  name: ansible
verifier:
  name: ansible
