---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    _openvpn_verify_requirements:
      default:
        - procps
      Debian:
        - net-tools
        - procps
      RedHat:
        - procps-ng
    openvpn_verify_requirements: "{{ _openvpn_verify_requirements[ansible_os_family] | default(_openvpn_verify_requirements['default']) }}"
<<<<<<< HEAD
    contents: "{{ lookup('file','/etc/openvpn/server.conf') }}"
=======
>>>>>>> dfbdb3f9a410ae30a2c4e13da3875640ee0c97e5

  tasks:
    - name: Install requirements
      ansible.builtin.package:
        name: "{{ openvpn_verify_requirements }}"
      notify:
        - Uninstall requirements

    - name: Gather facts on listening ports
      community.general.listen_ports_facts:

    - name: Check if UPD port 1194 is listening
      assert:
        that:
          - 1194 in ansible_facts.udp_listen | map(attribute='port')
        quiet: yes

<<<<<<< HEAD
    - name: Print file
      ansible.builtin.debug:
        msg: "the content file is {{ contents }}"

=======
>>>>>>> dfbdb3f9a410ae30a2c4e13da3875640ee0c97e5
  handlers:
    - name: Uninstall requirements
      ansible.builtin.package:
        name: "{{ openvpn_verify_requirements }}"
        state: absent
